### ISSUE TITLE
Create New Branch and Initialize Formatted index.html

### ISSUE THREAD

**Issue by NurjahanJ** [NurjahanJ/IS218-Final#11]
This issue is created to track the progress of starting a new branch for development and initializing a formatted `index.html` file for our project.

## Tasks
- [x] Create a new branch named `code-start`.
- [x] On the new branch, create an `index.html` file.
- [x] Format the `index.html` file with the basic HTML5 structure.

## Goals
The purpose of this task is to set up a foundational structure for our web development, ensuring that we have a solid base to start coding on.
